### ISSUE TITLE
Out of Memory when query dns.google for instacart.com

### ISSUE THREAD

**Issue by ulysses425** [gera2ld/async_dns#21]
When I query "instacart.com", the process stuck and the memory increased dramatically, took 100% in a few seconds, would you please have a look at the case? Great thanks!

```
async def main():
    async with DoHClient() as client:
        result = await client.query('https://dns.google/dns-query', 'instacart.com', 255)
        print('query:', result)
asyncio.run(main())
```

**Comment by gera2ld** [comment]
Fixed in e610bbbe3633d7efd4e8c8ebcfb4ed50026a4550

Please upgrade `async_dns` or reinstall `async-doh`.
