### ISSUE TITLE
没有实现 DNS  server 的RRHeader?

### ISSUE THREAD

**Issue by hysia** [gera2ld/async_dns#4]
类似 `twisted.names.dns.RRHeader`

**Comment by gera2ld** [comment]
就是这里的[Record](https://github.com/gera2ld/async_dns/blob/5a0896853ebd6940736651fe6f464880773898a9/async_dns/base.py#L167)吗？

**Comment by hysia** [comment]
不一样，还要有个头的包装

**Comment by gera2ld** [comment]
不是很懂你的需求。。
