### ISSUE TITLE
Documentation on resolver.query_remote()

### ISSUE THREAD

**Issue by killswitch-GUI** [gera2ld/async_dns#5]
Do you have any Docs laying around or API  examples for resolver.query_remote()? 

Thanks for this 👍 project

**Comment by gera2ld** [comment]
Sorry, there is no docs yet.
`resolver.query_remote` is a method used internally, you should use `resolver.query` instead.

Anyway it can be used like this:
```python
fqdn = 'www.google.com'
qtype = types.A
res = DNSMessage()
has_result = await resolver.query_remote(res, fqdn, qtype)
if has_result:
    print(res)
```

**Comment by ghost** [comment]
How would this tie in to resolve multiple hosts in a list? I want to use this for generating ASN and IP address lists for lists of hostnames, in a tool that is used by firewalls to generate aliases updated on schedule.

**Comment by gera2ld** [comment]
Closing since this API is outdated. Basic usage examples are included in README.

Feel free to open a new issue if you have other questions.
